// - LOGIN
export const REGISTER = "REGISTER";
export const DELETE_REGISTER = "DELETE_REGISTER";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_INVITED = 'LOGIN_INVITED';
export const LOGIN_START = 'LOGIN_START';
export const DATA_USER = 'DATA_USER';
export const DATA_USER_PROFILE = 'DATA_USER_PROFILE';
export const SAVE_ALL_CREDICT_CARD = 'SAVE_ALL_CREDICT_CARD'; 
export const SET_DEFAULT_CARD = 'SET_DEFAULT_CARD';
export const SET_COIN_BALANCE = 'SET_COIN_BALANCE';
export const SET_USED_COUPON = 'SET_USED_COUPON';
//FIREBASE
export const SAVE_TOKEN = 'SAVE_TOKEN';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
// CUIQLY
export const SHOW_TUTORIAL = 'SHOW_TUTORIAL';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_LOCATIONPUB = 'CHANGE_LOCATIONPUB';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const SET_ACTIONS_APP = 'SET_ACTIONS_APP';
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_APP_ACTION = 'SET_APP_ACTION';
// - CHAT
export const CHAT_STATUS = 'CHAT_STATUS';
export const OPEN_CHAT = 'OPEN_CHAT'; 
export const CHANGE_TO_READ = 'CHANGE_TO_READ'; 
// - CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const CURRENT_CART = 'CURRENT_CART';
export const CHANGE_COINS = 'CHANGE_COINS';
export const SELECT_CARD = 'SELECT_CARD';
export const DELETE_CURRENT_CART = 'DELETE_CURRENT_CART';
export const SET_USED_CARD = 'SET_USED_CARD';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'; 
// PRODUCT
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
// PRODUCTS FEATURE
export const PRODUCTS_FEATURED = 'PRODUCTS_FEATURED';
export const CHANGE_FEATURED = 'CHANGE_FEATURED';
//BORRAR
export const ADD_QUANT_PRODUC_CART = 'ADD_QUANT_PRODUC_CART';
export const REMOVE_QUANT_PRODUC_CART = 'REMOVE_QUANT_PRODUC_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const CLEAR_CART = 'CLEAR_CART';
//NOTIFICATIONS
export const SAVE_ALL_NOTI = 'SAVE_ALL_NOTI';
export const NOTIF_UPDATE_NOT_READ = 'NOTIF_UPDATE_NOT_READ';
export const NOTIF_HIDDEN_ICON = 'NOTIF_HIDDEN_ICON';
export const CHANGE_READ_STATUS = 'CHANGE_READ_STATUS';
