// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_TOKEN = 'LOGIN_TOKEN';
export const LOGOUT = 'LOGOUT';
//FIREBASE
export const SAVE_TOKEN = 'SAVE_TOKEN';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
//LOGO
export const SET_FINISH_LOGO = 'SET_FINISH_LOGO';
//NetInfo
export const UPDATE_DATA_CONNECT = 'UPDATE_DATA_CONNECT';
//APP INFO
export const SET_INFO_DEVICE = 'SET_INFO_DEVICE';
//TOKEN LIST SHOW
export const SET_TOKENLIST_VALIDATE = 'SET_TOKENLIST_VALIDATE';
export const SET_TOKENLIST_REFRESH = 'SET_TOKENLIST_REFRESH';
